# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true

# Expo
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false
expo.useLegacyPackaging=false
EX_DEV_CLIENT_NETWORK_INSPECTOR=true

# Custom
newArchEnabled=false
kotlinVersion=2.1.21
